### ISSUE TITLE
[naming optimization] consider shorten nickname petalisp

### ISSUE THREAD

**Issue by Inc0n** [marcoheisig/Petalisp#10]
Hi, sometimes it's better style to prefix package name. But if the package name is too long, it would be too verbose.
Therefore, please consider the nicknames:
 - p
 - pl

**Comment by marcoheisig** [comment]
Thanks for your feedback.

There are some things to consider, though:

- I make sure that the Petalisp package doesn't export any symbols that collide with Common Lisp and frequently used libraries like closer-mop or alexandria.  So it is relatively safe to `:use` Petalisp in a package definition, at least for scripting.

- If using other packages than CL creeps you out, there is the possibility to use [package-local-nicknames](https://github.com/phoe/trivial-package-local-nicknames).

- My preferred solution is to use `:import-from` to import only the most frequently used Petalisp symbols like `α`, `β`, and `reshape`.  This avoids most of the problems of `:use`-ing other packages.  And it keeps the very frequently used Petalisp symbol names short.

- At nickname like `p` or `pl` has a high risk of colliding with other package names or nicknames.  (For example, there is a collision on Quicklisp between the binary-types and bordeaux-threads, because they both chose the nickname 'bt'.  I'd rather avoid this issue.)

So right now I am not convinced I should introduce such very short nicknames.

What do you think?

**Comment by Inc0n** [comment]
Actually petalisp is not that long of a name, I have came to realize.

The introduction of nicknames collision, in attempt of solving my suggested naming optimization, is yet another problem to take care of.

The package-local-nicknames, however, would be a good solution for me instead.

**Comment by equwal** [comment]
For what it's worth, most projects avoid declaring their own nicknames with the idea that it is straightforward to declare your own when importing them in ASDF, but not straightforward to deal with name conflicts (where the source code has to be patched). So doing a two letter nickname is actually a _bug_ in the source when it happens to conflict.
